version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      hoge:
        patterns:
          - 'pry-rails'
          - 'rubocop-rails'
