name: Move dependabot pull requests into To do

on:
  pull_request_target:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-project-card@v1
        with:
          project-location: KanaeMurakami
          project-name: test
          column-name: To do
          issue-number: ${{ github.event.number }}
          token: ${{ secrets.GHPROJECT_TOKEN }}
